[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_counter = "CWrLG7by7VXJ7V4XZwGzErt1fGE8FXSRYZ2Wf4hx2Caa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://clean-blissful-patron.solana-devnet.quiknode.pro/0c1c6fd14118b66a3e7f4f5edc764738e801996d/"
wallet = "/home/chuo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/anchor-counter.ts"
